[package]
name = "julia-visualizer"
version = "0.1.0"
edition = "2024"

[dependencies]
audioviz = "0.6.0"
bytemuck = { version = "1.23.2", features = ["derive"] }
cpal = "0.16.0"
env_logger = "0.11.8"
log = "0.4.27"
pollster = "0.4.0"
wgpu = "26.0.1"
winit = "0.30.12"
